language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.1
  - 7.2
  - 7.3

sudo: required

addons:
  firefox: "35.0.1"
  postgresql: "9.4"

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=2

matrix:
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE CI_PLUGIN=2
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE CI_PLUGIN=2
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE CI_PLUGIN=2
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE CI_PLUGIN=2
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=2
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master CI_PLUGIN=2

before_install:
  - sudo hostname short-hostname
  - phpenv config-rm xdebug.ini
  - cd ../..
  - if [ "$CI_PLUGIN" = 2 ]; then
      nvm install 8;
      nvm use 8;
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
    else
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [ "$CI_PLUGIN" = 2 ]; then
      moodle-plugin-ci savepoints || travis_terminate 1;
      moodle-plugin-ci grunt || travis_terminate 1;
    else
      moodle-plugin-ci csslint || travis_terminate 1;
      moodle-plugin-ci jshint || travis_terminate 1;
      moodle-plugin-ci shifter || travis_terminate 1;
    fi
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
