language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2

sudo: required

addons:
  firefox: "35.0.1"
  postgresql: "9.4"

services:
  - mysql

matrix:
  include:
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master           CI_PLUGIN=3
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master           CI_PLUGIN=3
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master           CI_PLUGIN=3
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master           CI_PLUGIN=3
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE CI_PLUGIN=3
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE CI_PLUGIN=3
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=master           CI_PLUGIN=3
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master           CI_PLUGIN=3

before_install:
  - sudo hostname short-hostname
  - phpenv config-rm xdebug.ini
  - cd ../..
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - if [ "$CI_PLUGIN" = 3 ]; then
      composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - elif [ "$CI_PLUGIN" = 2 ]; then
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
    else
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [ "$CI_PLUGIN" = 3 ] || [ "$CI_PLUGIN" = 2 ]; then
      moodle-plugin-ci savepoints || travis_terminate 1;
      moodle-plugin-ci grunt || travis_terminate 1;
    else
      moodle-plugin-ci csslint || travis_terminate 1;
      moodle-plugin-ci jshint || travis_terminate 1;
      moodle-plugin-ci shifter || travis_terminate 1;
    fi
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
